version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    govet:
      check-shadowing: true

    gocyclo:
      min-complexity: 15

    dupl:
      threshold: 100

    goconst:
      min-len: 2
      min-occurrences: 2

    misspell:
      locale: US

    lll:
      line-length: 140

    goimports:
      local-prefixes: detectviz-platform

    funlen:
      lines: 100
      statements: 50

    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
