global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus 自身監控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Detectviz 平台 API 服務
  - job_name: "detectviz-api"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  # Node Exporter - 系統指標
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor - 容器指標
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # OTEL Collector 指標
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]

  # Grafana 指標
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # Jaeger 指標
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
# 存儲配置 - 使用命令行參數或環境變量設置
# --storage.tsdb.retention.time=15d
# --storage.tsdb.retention.size=10GB
