version: "3.9"
services:
  alloy:
    image: grafana/alloy:latest
    command: ["run", "/etc/alloy/config.alloy"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy/alloy.river:/etc/alloy/config.alloy:ro
    depends_on:
      - loki
      - tempo
      - mimir
      - pyroscope

  loki:
    image: grafana/loki:2.9.0
    ports: [ "3100:3100" ]

  tempo:
    image: grafana/tempo:2.6.0
    ports: [ "3200:3200", "4317:4317" ]

  mimir:
    image: grafana/mimir:2.12.0
    command: ["-target=all,alertmanager-ruler"]
    ports: [ "9009:9009" ]

  pyroscope:
    image: grafana/pyroscope:1.6.0
    ports: [ "4040:4040" ]
